'use client';

import React from 'react';
import type { Metadata } from 'next';
import Providers from '@/redux/provider';
import { Center, ChakraProvider, Flex, extendTheme } from '@chakra-ui/react';
import UserLayout from '@/common/layouts/user';
import 'react-quill/dist/quill.snow.css';
import Category from '@/components/public/Category';
import { usePathname } from 'next/navigation';

// export const metadata: Metadata = {
//   title: 'Coffee morning',
//   description: 'Generated by create next app',
// };

const theme = extendTheme({
  colors: {
    primary: '#EA8025',
  },
});

interface Props {
  children: React.ReactNode;
}

const RootLayout: React.FC<Props> = ({ children }) => {
  const pathname = usePathname();
  const pathsToCheck = ['/signin', '/signup'];
  const isApplyCommonLayout: boolean = pathsToCheck.some((path: string) => pathname.includes(path));
  const isProductsPage: boolean = pathname.includes('/collections');

  //   <ChakraProvider>
  //   {isApplyCommonLayout ? (
  //     <Providers>{children}</Providers>
  //   ) : (
  //     <Providers>
  //       <Layout>{children}</Layout>
  //     </Providers>
  //   )}
  // </ChakraProvider>

  return (
    <html lang="en">
      <head />
      <body>
        <ChakraProvider theme={theme}>
          {isProductsPage ? (
            <Providers>
              <UserLayout>
                <main>
                  <Center marginBottom="200px">
                    <Flex width="1200px" marginY="10">
                      <Category />
                      {children}
                    </Flex>
                  </Center>
                </main>
              </UserLayout>
            </Providers>
          ) : (
            <Providers>
              <UserLayout>{children}</UserLayout>
            </Providers>
          )}
        </ChakraProvider>
      </body>
    </html>
  );
};

export default RootLayout;
