Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true

Naming/MethodName:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 99
