source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.6'

# gem 'bcrypt', '~> 3.1.7'
# gem 'redis', '~> 4.0'
gem "rack-attack"
gem 'active_model_serializers', '0.10.0.rc4'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'cancancan'
gem 'coverband'
gem 'devise', '~> 4.8.1'
gem 'doorkeeper', '~> 5.4.0'
gem 'dotenv-rails', groups: [:development, :test]
gem 'elasticsearch-model'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'rack-cors'
gem 'rails', '~> 6.1.7', '>= 6.1.7.6'
gem 'rollbar'
gem 'rubocop', '~> 0.90.0', require: false # make sure .codeclimate.yml matches this
gem 'rubocop-performance', '~> 1.8.1', require: false
gem 'rubocop-rails', '~> 2.8.1', require: false
gem 'rswag-api'
gem 'rswag-ui'
gem 'thread_safe'

group :development, :test do
  gem "rspec-rails"
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry-rails'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
  gem 'annotate', '~> 3.2.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem "graphql", "~> 2.1"
gem 'graphiql-rails', "~> 1.9.0", group: :development
